//! The embedded models snapshot — the same artifact the Go backend embeds
//! (backend/internal/httpapi/models_snapshot.json), generated by
//! `bun run gen:models-snapshot`. It carries:
//!   - the static provider catalog (models + alias maps)
//!   - the `nativeChatTransports` map: which providers are safe to proxy
//!     natively (plain OpenAI wire format, single URL, Bearer auth)
//!
//! Embedding it means the Rust binary needs no Node round-trip for /v1/models
//! or for model→provider resolution on the chat path.

use once_cell::sync::Lazy;
use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct NativeChatTransport {
    #[serde(rename = "baseUrl")]
    pub base_url: String,
    #[serde(default)]
    pub headers: std::collections::HashMap<String, String>,
    #[serde(rename = "authHeader", default)]
    pub auth_header: String,
    #[serde(rename = "authScheme", default)]
    pub auth_scheme: String,
    #[serde(rename = "timeoutMs", default)]
    #[allow(dead_code)]
    pub timeout_ms: i64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct SnapModel {
    pub id: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub kind: String,
    #[serde(rename = "upstreamId", default)]
    pub upstream_id: String,
    /// Snapshot only writes `nativeChat` when true, so absent means "unknown",
    /// NOT false. Only an explicit false marks the model non-native.
    #[serde(rename = "nativeChat", default)]
    pub native_chat: Option<bool>,
    /// {input,output,cached,cache_creation,reasoning} $/Mtok for catalog UI.
    #[serde(default)]
    pub pricing: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct ModelsSnapshot {
    #[serde(rename = "providerModels", default)]
    provider_models: std::collections::HashMap<String, Vec<SnapModel>>,
    #[serde(rename = "providerModelsOrder", default)]
    #[allow(dead_code)]
    provider_models_order: Vec<String>,
    #[serde(rename = "idToAlias", default)]
    #[allow(dead_code)]
    id_to_alias: std::collections::HashMap<String, String>,
    /// alias (provider token) -> canonical providerId
    #[serde(rename = "aliasToProviderId", default)]
    alias_to_provider_id: std::collections::HashMap<String, String>,
    #[serde(rename = "providerAlias", default)]
    #[allow(dead_code)]
    provider_alias: std::collections::HashMap<String, String>,
    #[serde(rename = "nativeChatTransports", default)]
    native_chat_transports: std::collections::HashMap<String, NativeChatTransport>,
    /// legacy alias map: provider token -> providerId (older snapshot field)
    #[serde(rename = "providerLookup", default)]
    provider_lookup: std::collections::HashMap<String, String>,
}

/// Resolve a provider token (e.g. "openrouter", "or", "anthropic") to its
/// canonical providerId. Mirrors Go's `snapshot.ProviderLookup[providerToken]`.
impl ModelsSnapshot {
    fn resolve_provider(&self, token: &str) -> Option<&str> {
        // providerLookup first (newer snapshots), then aliasToProviderId.
        if let Some(pid) = self.provider_lookup.get(token) {
            return Some(pid.as_str());
        }
        self.alias_to_provider_id.get(token).map(|s| s.as_str())
    }
}

static SNAPSHOT_RAW: &[u8] = include_bytes!("models_snapshot.json");

static SNAPSHOT: Lazy<ModelsSnapshot> = Lazy::new(|| {
    serde_json::from_slice(SNAPSHOT_RAW)
        .expect("snapshot: failed to parse embedded models_snapshot.json — regenerate via `bun run gen:models-snapshot`")
});

/// Result of resolving a `providerToken/model` request.
#[derive(Debug, Clone)]
pub struct ResolvedModel {
    pub provider_id: String,
    pub upstream_model: String,
    pub transport: NativeChatTransport,
}

/// Resolve a full `<providerToken>/<modelId>` string into a provider + upstream
/// model + transport, exactly as the Go native path does
/// (chat_resolver.go resolveNativeChatBase). Returns None when the provider is
/// unknown or has no native transport (caller should fall through / error).
pub fn resolve(model: &str) -> Option<ResolvedModel> {
    let (provider_token, model_id) = model.split_once('/')?;
    let provider_id = SNAPSHOT.resolve_provider(provider_token)?.to_string();

    // Transport must exist with a base URL — otherwise this provider needs Node.
    let transport = SNAPSHOT.native_chat_transports.get(&provider_id)?.clone();
    if transport.base_url.is_empty() {
        return None;
    }

    let listed = SNAPSHOT
        .provider_models
        .get(&provider_id)
        .and_then(|models| models.iter().find(|m| m.id == model_id && m.kind == "llm"));

    // Only an explicit nativeChat:false routes this model to Node — the flag is
    // absent on most entries, and absence must keep the native passthrough.
    if listed.is_some_and(|m| m.native_chat == Some(false)) {
        return None;
    }

    // Map client model id → upstream id when configured; unknown/new ids pass
    // through unchanged until the next snapshot regeneration.
    let upstream_model = match listed {
        Some(m) if !m.upstream_id.is_empty() => m.upstream_id.clone(),
        Some(m) => m.id.clone(),
        None => model_id.to_string(),
    };

    Some(ResolvedModel {
        provider_id,
        upstream_model,
        transport,
    })
}

/// Public catalog for GET /v1/models. Returns the OpenAI-compatible model list
/// (id + owned_by) built from the embedded snapshot — same shape the Go handler
/// serves for the static-only case.
pub fn openai_model_list() -> serde_json::Value {
    let mut data = Vec::new();
    for (provider, models) in &SNAPSHOT.provider_models {
        for m in models {
            if m.kind != "llm" {
                continue;
            }
            data.push(serde_json::json!({
                "id": m.id,
                "object": "model",
                "owned_by": provider,
            }));
        }
    }
    serde_json::json!({ "object": "list", "data": data })
}

/// Rich catalog for the dashboard Models page (GET /api/models): every
/// provider's models with kind, native flag, upstream mapping and $/Mtok
/// pricing so the UI can build searchable tables without guessing.
pub fn dashboard_model_catalog() -> serde_json::Value {
    let mut order: Vec<String> = SNAPSHOT.provider_models_order.clone();
    let mut keys: Vec<&String> = SNAPSHOT.provider_models.keys().collect();
    keys.sort();
    for k in keys {
        if !order.iter().any(|o| o == k) {
            order.push(k.clone());
        }
    }
    let mut providers_out: Vec<serde_json::Value> = Vec::new();
    for provider in &order {
        let Some(models) = SNAPSHOT.provider_models.get(provider) else {
            continue;
        };
        let has_transport = SNAPSHOT
            .native_chat_transports
            .get(provider)
            .map(|t| !t.base_url.is_empty())
            .unwrap_or(false);
        let models_json: Vec<serde_json::Value> = models
            .iter()
            .map(|m| {
                let pricing = m.pricing.as_ref();
                serde_json::json!({
                    "id": m.id,
                    "name": m.name,
                    "kind": m.kind,
                    "nativeChat": m.native_chat,
                    "upstreamId": m.upstream_id,
                    "inputPrice": pricing.and_then(|p| p.get("input")).and_then(|v| v.as_f64()),
                    "outputPrice": pricing.and_then(|p| p.get("output")).and_then(|v| v.as_f64()),
                })
            })
            .collect();
        providers_out.push(serde_json::json!({
            "provider": provider,
            "hasNativeTransport": has_transport,
            "models": models_json,
        }));
    }
    serde_json::json!({ "providers": providers_out })
}
